name: webview_cookie_manager_example
description: Demonstrates how to use the webview_cookie_manager plugin.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2

  webview_cookie_manager:
    path: ../
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true